### ISSUE TITLE
Database Not Provided!

### ISSUE THREAD

**Issue by Shahidali0077** [utkarshsingh341/webbd.xyz#1]
hello brother hope you doing well but the issue is the here is you are not providing db file so i request you to please provide db file for it
![issue](https://github.com/utkarshsingh341/webbd.xyz/assets/114554381/26ae5a5e-dcb1-4ae8-8cda-0996f0511105)

**Comment by utkarshsingh341** [comment]
You should not try and copy paste other people's projects. That is not what Github is for

**Comment by utkarshsingh341** [comment]
Please email me if you need the db file
